version: '3'

volumes:
    fatotabot-pg:
        external: true

services:
  db:
    volumes:
      - fatotabot-pg:/var/lib/postgresql/data
    image: postgres:9.6.4-alpine
    environment:
      POSTGRES_USER: YOUR_DB_USER
      POSTGRES_PASSWORD: YOUR_DB_PASSWORD
      POSTGRES_DB: YOUR_DB_NAME
    expose:
      - 5432
  
  web:
    build: .
    image: fatotabot:local
    volumes:
      - ./:/fatotabot
    working_dir: /fatotabot
    command: bash -c "bundle install && bundle exec ruby bot.rb"
    stdin_open: true
    tty: true
    depends_on:
      - db
